# Generated by Django 4.2.13 on 2024-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='profile_pictures'),
        ),
    ]
