# Generated by Django 4.2.13 on 2024-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finished_date',
            field=models.DateField(null=True),
        ),
    ]
